### ISSUE TITLE
Pixinsight image container and starnet2 plugin issue

### ISSUE THREAD

**Issue by ghost** [nekitmm/starnet#32]
Pixinsight
problem in batch treatement with image container and linear data. The linear data checked is not transmited at image container so black artifacts...
Thank you i love starnet2

**Comment by ArekSredzki** [comment]
I've run into the same issue as well. It'd be great to have the ability to run this in batches since it's much faster than StarXTerminator. It makes a big difference for those of us doing comet processing without a CUDA-capable GPU :)

**Comment by ghost** [comment]
OK, AreK, I use also CUDA, it's really much faster. And it's also for comet !

**Comment by ArekSredzki** [comment]
I can't wait to buy a new Nvidia GPU next week so I can bring these processing times down :)
I have a Radeon RX 6900 XT but sadly DirectML doesn't work for TF2 yet.
Currently, each frame is taking 8mins with StarXTerminator on my 12th gen i9 CPU 😭 

That was a bit of an aside, but it'd be great to fix StarNet2's ImageContainer support.

**Comment by nekitmm** [comment]
Closing as this repo doesn't have anything to do w/ PI plugin. Will look into mentioned requests when I got time, for now I am not even sure what are image containers in PI. Thank you!

**Comment by ghost** [comment]
Nikita, thank you for your comment. To help you : 
-the plugin work very well for single frame. Thank you so much
-the problem, is when we use "image container" for bath processing : 
When I look to the "instance source code" of the plugin window, we see only a parameter for the mask : 
"var P = new StarNet2;
P.stride = StarNet2.prototype.itemOne;
P.mask = false;
"
I think the info of the checked box for linear data is not seen by image container. 
Perharps, it will be ok, adding two lines (ex P.linear...) into the instance source code ?

**Comment by nekitmm** [comment]
Hey, just a quick update: I've updated the code and released updated PI plugin. Please feel free to reach out to me on astrobin or cloudynights if there are further questions/problems! Thank you!

**Comment by ghost** [comment]
Thank you Nikita for this quick update.
I just test. no effect, still the same problem. So sorry. Lets continu on cloudynights.

**Comment by nekitmm** [comment]
To be honest, I kinda new it wasn't going to work - linear option relies on user-set STF parameters to stretch an image. I just pushed another patch that solves this - now if you check 'Linear data' option, but STF is not set, it will auto-stretch image. This solves the problem with Image container. Feel free to update and check it out!

**Comment by ghost** [comment]
Thank you Nikita !
Now It's working well ! good idea to work around this problem.
For info, I use CUDA 11.8 with tensorflow 2.9.0 GPU thank to a post read on pixinsight forum. it goes 20s less other tensorflow
